services:
  postgres:
    container_name: postgres-sql-cac
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: chatAppDb

    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - chatApp-net
    restart: unless-stopped
  keycloak:
    container_name: keycloak-cac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      chatApp-net:
    command:
      - "start-dev"

networks:
  chatApp-net:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local